spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${SUPOS_HOSTED_HOST:lake-sql-mariadb-95c7b626dc.default.svc}:${SUPOS_HOSTED_PORT:3306}/${SUPOS_HOSTED_DBNAME:apsdatabase}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&connectTimeout=86400&socketTimeout=86400&autoReconnect=true&autoReconnectForPools=true
      username: ${SUPOS_HOSTED_USERNAME:supos_549bed47}
      password: ${SUPOS_HOSTED_PASSWORD:d18391335b2750}
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1
      validation-query-timeout: 15
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 300000
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
      mode: always
      continue-on-error: true

logging:
  level:
    root: info
    com.supos.assets: debug
    com.alibaba.druid.pool: debug
    org.springframework.jdbc.core: debug
#Debezium配置
customer:
  datasource:
    host: lake-sql-mariadb-95c7b626dc.default.svc
    port: 31306
    database: 47.236.10.165
    username: supos_549bed47
    password: d18391335b2750
